# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table ingredient (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  quantity                      integer not null,
  parent_recipe_id              bigint,
  constraint pk_ingredient primary key (id)
);

create table recipe (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  preparation_time              integer not null,
  difficulty                    integer not null,
  constraint pk_recipe primary key (id)
);

-- foreign keys and indices
create index ix_ingredient_parent_recipe_id on ingredient (parent_recipe_id);
alter table ingredient add constraint fk_ingredient_parent_recipe_id foreign key (parent_recipe_id) references recipe (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table ingredient drop constraint if exists fk_ingredient_parent_recipe_id;
drop index if exists ix_ingredient_parent_recipe_id;

-- drop all
drop table if exists ingredient;

drop table if exists recipe;

